In [39]:
def MagrginProp(p_labels,p_feature,keys_feature):
    # let's compute marginal probabilities of labels values
  p_feature = np.sum(p_labels * p_feature, axis=1)
  # we create a pandas dataframe to visualize the table more familiar
  df_p_feature = pd.DataFrame(p_feature, keys_feature)

  # possibilities of buying values
  return df_p_feature

In [40]:
def JointProp(train_dataset,featurecolumn,labelcolumn="Car Acceptability"):
    # unique values of feature column
  keys_feature = np.array(train_dataset[featurecolumn].unique())

  # unique values of label column
  keys_labels = np.array(train_dataset[labelcolumn].unique())

  # let's initiate a matrix to hold counts 
  p_feature_given_label = np.zeros((len(keys_feature), len(keys_labels)))

  # zip only feature and clazz label
  for i in zip(train_dataset[featurecolumn], train_dataset[labelcolumn]):
      # get index of current feature value
      index_feature = np.where(keys_feature == i[0])
      
      # get index of current label value
      index_label = np.where(keys_labels == i[1])
      
      # increment 1 the count of the intersection of feature x label pair.
      p_feature_given_label[[index_feature], [index_label]] += 1

  # we create a pandas dataframe to visualize the table more familiar
  df_p_feature_given_label = pd.DataFrame(p_feature_given_label, keys_feature, keys_labels)
  # let's normalize the possibilities
  p_feature_given_label = p_feature_given_label / np.sum(p_feature_given_label, axis=0, keepdims=True)

  # we create a pandas dataframe to visualize the table more familiar
  df_p_feature_given_label = pd.DataFrame(p_feature_given_label, keys_feature, keys_labels)

  # possibilities of buying values given class
  return df_p_feature_given_label

In [41]:
# for data manipulation
import pandas as pd
# for array operations
import numpy as np
from sklearn.model_selection import train_test_split
# read dataset from csv file
df = pd.read_csv("car_data.csv",encoding_errors='ignore')

In [42]:
df.head()

,Buying Price,Maintenance Price,Number of Doors,Capacity,Size of Luggage Boot,Car Safety,Car Acceptability
0,vhigh,vhigh,2,2,small,low,unacc
1,vhigh,vhigh,2,2,small,med,unacc
2,vhigh,vhigh,2,2,small,high,unacc
3,vhigh,vhigh,2,2,med,low,unacc
4,vhigh,vhigh,2,2,med,med,unacc

In [43]:
train_dataset,test_dataset=train_test_split(df, test_size=0.25, random_state=42)

In [44]:
#extract unique labels and make counter for each one

keys_labels = np.array(train_dataset["Car Acceptability"].unique())
keys_count=np.zeros((len(keys_labels)))

In [45]:
print(f"unique labels: {keys_labels}")
print(f"keys counter: {keys_count}")

unique labels: ['unacc' 'acc' 'good' 'vgood']
keys counter: [0. 0. 0. 0.]

In [46]:
for currentLabel in train_dataset["Car Acceptability"]:
    # get index of current Car Acceptability value
    index_label = np.where(keys_labels == currentLabel)
    # increment 1 the count of the label 
    keys_count[index_label] += 1
    
# let's normalize the possibilities
p_labels = keys_count / np.sum(keys_count, axis=0, keepdims=True)
df_p_labels = pd.DataFrame(p_labels, keys_labels)

In [47]:
df_p_labels

              0
unacc  0.706790
acc    0.216821
good   0.041667
vgood  0.034722

In [48]:
joint_buying=JointProp(train_dataset,featurecolumn="Buying Price",labelcolumn="Car Acceptability")
joint_buying

          unacc       acc      good     vgood
med    0.235808  0.288256  0.333333  0.377778
high   0.252183  0.288256  0.000000  0.000000
low    0.219432  0.227758  0.666667  0.622222
vhigh  0.292576  0.195730  0.000000  0.000000

In [49]:
joint_doors=JointProp(train_dataset,featurecolumn="Number of Doors",labelcolumn="Car Acceptability")
joint_doors

          unacc       acc      good     vgood
4      0.237991  0.266904  0.296296  0.311111
2      0.277293  0.199288  0.259259  0.155556
3      0.253275  0.241993  0.203704  0.222222
5more  0.231441  0.291815  0.240741  0.311111

In [50]:
joint_capacity=JointProp(train_dataset,featurecolumn="Capacity",labelcolumn="Car Acceptability")
joint_capacity

         unacc       acc      good     vgood
4     0.269651  0.516014  0.537037  0.533333
2     0.465066  0.000000  0.000000  0.000000
more  0.265284  0.483986  0.462963  0.466667

In [51]:
joint_Boot=JointProp(train_dataset,featurecolumn="Size of Luggage Boot",labelcolumn="Car Acceptability")
joint_Boot

          unacc       acc      good     vgood
small  0.368996  0.284698  0.277778  0.000000
med    0.328603  0.345196  0.351852  0.333333
big    0.302402  0.370107  0.370370  0.666667

In [52]:
joint_Safety=JointProp(train_dataset,featurecolumn="Car Safety",labelcolumn="Car Acceptability")
joint_Safety

         unacc       acc      good  vgood
med   0.291485  0.459075  0.592593    0.0
high  0.228166  0.540925  0.407407    1.0
low   0.480349  0.000000  0.000000    0.0

In [53]:
joint_Maintenance=JointProp(train_dataset,featurecolumn="Maintenance Price",labelcolumn="Car Acceptability")
joint_Maintenance

          unacc       acc      good     vgood
high   0.269651  0.259786  0.000000  0.244444
low    0.208515  0.238434  0.685185  0.444444
vhigh  0.294760  0.181495  0.000000  0.000000
med    0.227074  0.320285  0.314815  0.311111

In [54]:
#Magrgin_buying=MagrginProp(p_labels,joint_buying.to_numpy(),np.array(train_dataset["Buying Price"].unique()))
#Magrgin_Maintenance=MagrginProp(p_labels,joint_Maintenance.to_numpy(),np.array(train_dataset["Maintenance Price"].unique()))
#Magrgin_Doors=MagrginProp(p_labels,joint_doors.to_numpy(),np.array(train_dataset["Number of Doors"].unique()))
#Magrgin_capacity=MagrginProp(p_labels,joint_capacity.to_numpy(),np.array(train_dataset["Capacity"].unique()))
#Magrgin_Boot=MagrginProp(p_labels,joint_Boot.to_numpy(),np.array(train_dataset["Size of Luggage Boot"].unique()))
#Magrgin_Safety=MagrginProp(p_labels,joint_Safety.to_numpy(),np.array(train_dataset["Car Safety"].unique()))

In [55]:
correct = 0
for idx, item in test_dataset.iterrows():
    alpha = 1
    denominator = 0
    possibilities = {}
    for cls in keys_labels:
        p = 1
        p *= (joint_buying[cls][item["Buying Price"]])
        p *= (joint_Maintenance[cls][item["Maintenance Price"]])
        p *= (joint_doors[cls][item["Number of Doors"]])
        p *= (joint_capacity[cls][item["Capacity"]])
        p *= (joint_Boot[cls][item["Size of Luggage Boot"]])
        p *= (joint_Safety[cls][item["Car Safety"]])
        p *= df_p_labels[0][cls]
        
        denominator += p
        
        possibilities[cls] = p
    # end of for loop
    
    possibilities.update({k: v / denominator for k, v in possibilities.items()})
    
    #print(possibilities)
    correct += max(possibilities, key=possibilities.get) == item["Car Acceptability"]
# end of for loop

print("accuracy: %d%%" % ((correct / len(test_dataset)) * 100))

accuracy: 83%